### ISSUE TITLE
[XRCE-DDS] 未来工作任务记录

### ISSUE THREAD

**Issue by kurisaW** [kurisaW/micro_ros_local#12]
目前根据 micro-xrce-dds-client仓库，参考借鉴freertos和posix接口写法，需要rtthread提供一系列APi接口，后续参考这些API，大致看看具体实现

主要根据该提交记录进行适配移植，同时结合下面这张图

* https://github.com/kurisaW/Micro-XRCE-DDS-Client/commit/07e5f51c9f4038438b62e3d1c5b1efe20542eae7

![image](https://github.com/kurisaW/micro_ros_rtthread_component/assets/98592772/39297827-0221-4155-9a4c-b706d6a182fe)

需要注意的是，在移植client的过程中需要做一次分析任务，因为有些文件似乎是不必要的，也有可能是额外提供的功能机制，但是在示例中还未得到实现

**Comment by kurisaW** [comment]
针对第一条Commit中的图片提示，对此进行任务分配

- [x] 1.目前CMakeLists.txt文件中的内容基本都写上去了，然后其中具体涉及到的文件实现参照下面的任务
- [x] 2.config.h.in这部分已经完成，具体参考下面的任务
- [x] 3.transport.h这部分已完成
- [x] 4.udp_transport_datagram_internal.h 该文件中已经提前加入RTT支持，但是其中具体的代码实现需要参考udp_transport_datagram_rtthread.c文件的实现
- [x] 5.编写udp_transport_datagram_rtthread.c



比较值得说明的一点是，在下面这个路径中，一些具体的构建配置需要在该文件中声明，比如目前默认使用的是posix标准

/usr/local/include/uxr/client/config.h

**Comment by kurisaW** [comment]
## rclc和xrce-dds-client

* rclc是ROS 客户端支持库 （rcl），RCLC 提供了上述便利函数，用于创建具有相应 RCL 类型的发布者、订阅、节点等实例。此外，它还为 C 提供了 rclc 执行器，类似于 C++ 的 rclcpp 执行器类。与 rclcpp Executor 相比，一个关键特性是它包含用于实现确定性时序行为的功能。

*  Micro XRCE-DDS 是一个实现 DDS-XRCE 协议的库，Micro XRCE-DDS 客户端向代理请求操作，以发布和/或订阅 DDS 全局数据空间中的主题。还支持 DDS-RPC 标准定义的远程过程调用，允许客户端根据请求/应答范式在 DDS 数据空间中进行通信。代理处理这些请求，并在订阅/回复操作的情况下发回包含操作状态结果和请求数据的响应。DDS 世界中的通信由专门 ProxyClient 负责创建客户端请求的 DDS 实体（如参与者、主题、发布者和订阅者）进行调解，这些实体可以与 DDS 全局数据空间进行交互。Micro XRCE-DDS 客户端和 Micro XRCE-DDS 代理之间的通信是通过多种内置传输实现的：UDPv4、UDPv6、TCPv4、TCPv6 和串行通信。此外，用户还可以生成自己的自定义传输。

**Comment by kurisaW** [comment]
## 参考资料阅读（底层框架学习重点聚焦这两个链接）

ROS2客户端C库：
* https://micro.ros.org/docs/concepts/client_library/introduction/

Micro XRCE-DDS-Client：
* https://micro.ros.org/docs/concepts/middleware/Micro_XRCE-DDS/

**Comment by kurisaW** [comment]
## 参考issue

在这两个issue中讲到了有关工具链脚本中，我们需要指定rtos相关的头文件

下面是可值得参考的toolchain.cmake文件内容

```cmake
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)

# I normally don't use this. Added to test with micro-ros examples
set(CMAKE_CROSSCOMPILING 1)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_AR arm-none-eabi-ar)
message("-- TOOLCHAIN AR ${CMAKE_AR}")
set(CMAKE_C_COMPILER arm-none-eabi-gcc)
message("-- TOOLCHAIN C COMPILER ${CMAKE_C_COMPILER}")
set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
message("-- TOOLCHAIN CXX COMPILER ${CMAKE_CXX_COMPILER}")
set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
message("-- TOOLCHAIN ASM COMPILER ${CMAKE_ASM_COMPILER}")
set(CMAKE_OBJCOPY arm-none-eabi-objcopy)
message("-- TOOLCHAIN OBJCOPY ${CMAKE_OBJCOPY}")
set(CMAKE_OBJDUMP arm-none-eabi-objdump)
message("-- TOOLCHAIN OBJDUMP ${CMAKE_OBJDUMP}")
set(CMAKE_SIZE arm-none-eabi-size)
message("-- TOOLCHAIN SIZE ${CMAKE_SIZE}")

# I normally don't use this. Added to test with micro-ros examples
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# Flags
set(C_COMMON_FLAGS "${C_COMMON_FLAGS} -mcpu=cortex-m7 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb")

# generates a separate ELF section for each function in the source file
set(C_COMMON_FLAGS "${C_COMMON_FLAGS} -ffunction-sections")

# Enables or disables the generation of one ELF section for each variable in the source file
set(C_COMMON_FLAGS "${C_COMMON_FLAGS} -fdata-sections")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${C_COMMON_FLAGS}")

# Enables or disables the generation of code needed to support C++ exceptions.
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-exceptions")

# Disable generation of information about every class with virtual functions for use by the C++ runtime
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti")

# Do not emit the extra code to use the routines specified in the C++ ABI for thread-safe initialization of local statics.
# Reduce bin size
# TODO Do we have code that could have thread safety problem?
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-threadsafe-statics")

# Register destructors for objects with static storage duration with the __cxa_ atexit function rather than the atexit function
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-use-cxa-atexit")

# Add common C language flags
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${C_COMMON_FLAGS}")

add_definitions("-DUSE_HAL_DRIVER -DSTM32F746xx")

include_directories(SYSTEM
${CMAKE_CURRENT_LIST_DIR}/freertos-plus-posix/FreeRTOS-Plus-POSIX/include
${CMAKE_CURRENT_LIST_DIR}/freertos-plus-posix/FreeRTOS-Plus-POSIX/include/portable/st
${CMAKE_CURRENT_LIST_DIR}/freertos-plus-posix/include
${CMAKE_CURRENT_LIST_DIR}/freertos-plus-posix/include/private
${CMAKE_CURRENT_LIST_DIR}/freertos-plus-posix/include/FreeRTOS_POSIX
${CMAKE_CURRENT_LIST_DIR}/freertos-plus-posix/include/FreeRTOS_POSIX/sys
${CMAKE_CURRENT_LIST_DIR}/f7-drivers/STM32F7xx_HAL_Driver/Inc
${CMAKE_CURRENT_LIST_DIR}/f7-drivers/CMSIS/Device/ST/STM32F7xx/Include
${CMAKE_CURRENT_LIST_DIR}/f7-drivers/CMSIS/Include
${CMAKE_CURRENT_LIST_DIR}/f7-middlewares/Third_Party/FreeRTOS/Source/include
${CMAKE_CURRENT_LIST_DIR}/f7-middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
${CMAKE_CURRENT_LIST_DIR}/f7-middlewares/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1
)
# I normally don't use this. Added to test with micro-ros examples
set(__BIG_ENDIAN__ 0)
```

* https://github.com/micro-ROS/micro_ros_setup/issues/246
* https://github.com/micro-ROS/micro_ros_setup/issues/252

**Comment by kurisaW** [comment]
```bash
D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/util/time.c: In function 'uxr_nanos':
D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/util/time.c:62:19: warning: conversion to 'int64_t' {aka 'long long int'} from 'uint64_t' {aka 'long long unsigned int'} may change the sign of the result [-Wsign-conversion]
   62 |     return now_ms * 1000000;
      |            ~~~~~~~^~~~~~~~~
D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/udp/udp_transport_rtthread.c: In function 'uxr_init_udp_platform':
D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/udp/udp_transport_rtthread.c:41:38: warning: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Wsign-conversion]
   41 |     platform->server_addr.sin_port = htons(atoi(port));
      |                                      ^~~~~
D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/udp/udp_transport_rtthread.c:41:38: warning: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Wsign-conversion]
D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/udp/udp_transport_rtthread.c:42:40: warning: cast increases required alignment of target type [-Wcast-align]
   42 |     platform->server_addr.sin_addr = *((struct in_addr *)host->h_addr);
      |                                        ^
D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/udp/udp_transport_rtthread.c: In function 'uxr_read_udp_data_platform':
D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/udp/udp_transport_rtthread.c:106:5: warning: conversion to 'unsigned int' from 'int' may change the sign of the result [-Wsign-conversion]
  106 |     FD_SET(platform->sock, &readset);
      |     ^~~~~~
D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/udp/udp_transport_rtthread.c:106:5: warning: conversion to 'unsigned int' from 'int' may change the sign of the result [-Wsign-conversion]
In file included from D:/Desktop/rt-thread/components/net/netdev/include/arpa/inet.h:14,
                 from D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/ip_rtthread.c:4:
D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/ip_rtthread.c: In function 'uxr_locator_to_ip':
D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/ip_rtthread.c:45:89: warning: conversion to 'int32_t' {aka 'long int'} from 'long unsigned int' may change the sign of the result [-Wsign-conversion]
   45 |             result = (NULL != inet_ntop(AF_INET, locator->_.medium_locator.address, ip, (socklen_t)size));
      |                                                                                         ^~~~~~~~~~~~~~~
D:/Desktop/rt-thread/bsp/stm32/stm32f407-rt-spark/packages/micro_ros_rtthread_component/builder/micro/mcu/src/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/ip_rtthread.c:50:89: warning: conversion to 'int32_t' {aka 'long int'} from 'long unsigned int' may change the sign of the result [-Wsign-conversion]
   50 |             result = (NULL != inet_ntop(AF_INET6, locator->_.large_locator.address, ip, (socklen_t)size));
      |
```

**Comment by kurisaW** [comment]
## toolchain.cmake包含必需文件详细解决方案

我们理想的用户开发方式是直接克隆主仓仓库并下载micro-ros软件包的形式来搭建microros环境，其中micro库的编译和链接工作默认放在C盘，同时由于toolchain.cmake文件是存放在bsp下，对于cmake编译，最重要就是获取两个路径：
* RTT_ROOT_DIR
* BSP_ROOT_DIR

其中脚本的内容为：
```cmake
get_filename_component(script_path "${CMAKE_CURRENT_LIST_FILE}" ABSOLUTE)

string(REGEX MATCH "^(.*rt-thread)" RTT_ROOT_DIR "${script_path}")
string(REGEX MATCH "^(.*stm32f407-rt-spark)" BSP_ROOT_DIR "${script_path}")

include_directories(SYSTEM
${RTT_ROOT_DIR}/include              # kernel include
${RTT_ROOT_DIR}/components/finsh     # finsh include
${RTT_ROOT_DIR}/components/net/sal/include                      # #include <netdb.h>
${RTT_ROOT_DIR}/components/net/sal/include/socket               
${RTT_ROOT_DIR}/components/net/sal/include/socket/sys_socket    # #include <sys/socket.h>
${RTT_ROOT_DIR}/components/net/netdev/include
${RTT_ROOT_DIR}/components/net/netdev/include/arpa              # #include <arpa/inet.h>
${BSP_ROOT_DIR}                                                 # rtconfig.h
)
```

其中我们为了让用户一键式开发，对于cmake编译中所涉及到的1个参数：BSP_ROOT_DIR,需要出让内容编辑权限给用户，最好就是在配置XRCE-DDS的时候在env中直接给用户填写

**Comment by kurisaW** [comment]
## 2023.12.5

目前udp方式在micro XRCE-DDS 已经成功在星火spark上跑通，并且用户可以像在 DDS 中一样编写自定义 XML QoS，接下来有以下任务：

短期任务：
* 1.serial、tcp方式暂未测试，需要编写测试用例进行测试
* 2.目前的软件包仓库的构建脚本还存在一些问题，需要更好符合用户的使用体验，提升可移植性

## 长期任务
* 1.目前的例程还比较少，参考官方仓库移植一些demo到仓库中
* 2.为了验证micro XRCE-DDS的可行性，需要进行一次和 standard DDS 之间的通信，也就是说需要搭建一份标准DDS环境，然后使之与 micro XRCE-DDS 进行通讯
* 3.针对不同版本的microros需要提供一份合适的解决方案，在此issue中进行记录：https://github.com/kurisaW/micro_ros_rtthread_component/issues/13

**Comment by kurisaW** [comment]
```c
/*
 * Copyright (c) 2006-2020, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author       Notes
 * 2020/12/31     Bernard      Add license info
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <rtthread.h>

static struct rt_mutex test_lock1;
static struct rt_mutex test_lock2;

int main(void)
{
    printf("Hello RT-Thread!\n");


    return 0;
}

static void mutex_thread1_entry()
{
    rt_mutex_init(&test_lock1, "test_mutex1", 1);
    rt_mutex_take(&test_lock1, -1);
    rt_kprintf("test_mutex1!\n");
    rt_thread_delete(rt_thread_self());
    rt_schedule();
}

static void mutex_thread2_entry()
{
    // rt_mutex_init(&test_lock2, "test_mutex2", 1);
    // rt_mutex_take(&test_lock2, -1);
    rt_kprintf("test_mutex2!\n");
    // rt_thread_detach(rt_thread_self());
    // rt_schedule();
}

static int test(void)
{
    char thread2_stack[1024];

    rt_thread_t sem_th1 = rt_thread_create("mutex1_th", mutex_thread1_entry, RT_NULL, 1024, 25, 10);
    struct rt_thread sem_th2;
    rt_thread_init(&sem_th2, "mutex2_th", mutex_thread2_entry, RT_NULL, &thread2_stack[0], sizeof(thread2_stack), 26, 10);
    
    // rt_thread_startup(sem_th1);
    rt_thread_startup(&sem_th2);

    return 0;
}
MSH_CMD_EXPORT(test, test_sem);
```
